#!/bin/bash

APP_ANDROID_NAME=""
APP_ANDROID_VERSION=""
APP_ANDROID_BUILD_VERSION=""
APP_ANDROID_ID=""
APP_ANDROID_PACKAGE=""
APP_ANDROID_SCHEME=""

MIBOVEDA="miboveda"

TYPES=($MIBOVEDA)
APP_ANDROID_TYPE=$1

MIBOVEDA_NAME="Mi Bóveda"
MIBOVEDA_VERSION="1.0.0"
MIBOVEDA_BUILD_NUMBER=1
MIBOVEDA_BUNDLE_ID="com.miboveda.wallet"
MIBOVEDA_PACKAGE="com.miboveda.wallet"
MIBOVEDA_SCHEME="miboveda"

if ! [[ " ${TYPES[*]} " =~ " ${APP_ANDROID_TYPE} " ]]; then
    echo "Wrong app type."
    return 1 2>/dev/null
    exit 1
fi

case $APP_ANDROID_TYPE in
	$MIBOVEDA)
		APP_ANDROID_NAME=$MIBOVEDA_NAME
		APP_ANDROID_VERSION=$MIBOVEDA_VERSION
		APP_ANDROID_BUILD_NUMBER=$MIBOVEDA_BUILD_NUMBER
		APP_ANDROID_BUNDLE_ID=$MIBOVEDA_BUNDLE_ID
		APP_ANDROID_PACKAGE=$MIBOVEDA_PACKAGE
		APP_ANDROID_SCHEME=$MIBOVEDA_SCHEME
		;;
esac

export APP_ANDROID_TYPE
export APP_ANDROID_NAME
export APP_ANDROID_VERSION
export APP_ANDROID_BUILD_NUMBER
export APP_ANDROID_BUNDLE_ID
export APP_ANDROID_PACKAGE
export APP_ANDROID_SCHEME
