// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to `go/mweb.h`.
class MWebFlutter {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MWebFlutter(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MWebFlutter.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup)
      : _lookup = lookup;

  int StartServer(
    ffi.Pointer<ffi.Char> chain,
    ffi.Pointer<ffi.Char> dataDir,
    ffi.Pointer<ffi.Char> nodeUri,
    ffi.Pointer<ffi.Pointer<ffi.Char>> errMsg,
  ) {
    return _StartServer(
      chain,
      dataDir,
      nodeUri,
      errMsg,
    );
  }

  late final _StartServerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('StartServer');
  late final _StartServer = _StartServerPtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  void StopServer() {
    return _StopServer();
  }

  late final _StopServerPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>('StopServer');
  late final _StopServer = _StopServerPtr.asFunction<void Function()>();

  ffi.Pointer<ffi.Char> Addresses(
    ffi.Pointer<ffi.Char> scanSecret,
    int scanSecretLen,
    ffi.Pointer<ffi.Char> spendPubKey,
    int spendPubKeyLen,
    int i,
    int j,
  ) {
    return _Addresses(
      scanSecret,
      scanSecretLen,
      spendPubKey,
      spendPubKeyLen,
      i,
      j,
    );
  }

  late final _AddressesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Int, ffi.Pointer<ffi.Char>,
              ffi.Int, ffi.Int, ffi.Int)>>('Addresses');
  late final _Addresses = _AddressesPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Char>, int, int, int)>();
}

base class max_align_t extends ffi.Opaque {}

base class _GoString_ extends ffi.Struct {
  external ffi.Pointer<ffi.Char> p;

  @ptrdiff_t()
  external int n;
}

typedef ptrdiff_t = ffi.Long;

base class GoInterface extends ffi.Struct {
  external ffi.Pointer<ffi.Void> t;

  external ffi.Pointer<ffi.Void> v;
}

base class GoSlice extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  @GoInt()
  external int len;

  @GoInt()
  external int cap;
}

typedef GoInt = GoInt64;
typedef GoInt64 = ffi.LongLong;

const int NULL = 0;
