#!/bin/sh

APP_IOS_NAME=""
APP_IOS_VERSION=""
APP_IOS_BUILD_VERSION=""
APP_IOS_BUNDLE_ID=""

MIBOVEDA="miboveda"

TYPES=($MIBOVEDA)
APP_IOS_TYPE=$1

MIBOVEDA_NAME="Mi Bóveda"
MIBOVEDA_VERSION="1.0.0"
MIBOVEDA_BUILD_NUMBER=1
MIBOVEDA_BUNDLE_ID="com.miboveda.wallet"

if ! [[ " ${TYPES[*]} " =~ " ${APP_IOS_TYPE} " ]]; then
    echo "Wrong app type."
    exit 1
fi

case $APP_IOS_TYPE in
	$MIBOVEDA)
		APP_IOS_NAME=$MIBOVEDA_NAME
		APP_IOS_VERSION=$MIBOVEDA_VERSION
		APP_IOS_BUILD_NUMBER=$MIBOVEDA_BUILD_NUMBER
		APP_IOS_BUNDLE_ID=$MIBOVEDA_BUNDLE_ID
		;;
esac

export APP_IOS_TYPE
export APP_IOS_NAME
export APP_IOS_VERSION
export APP_IOS_BUILD_NUMBER
export APP_IOS_BUNDLE_ID
