#!/bin/sh

APP_MACOS_NAME=""
APP_MACOS_VERSION=""
APP_MACOS_BUILD_VERSION=""
APP_MACOS_BUNDLE_ID=""

MIBOVEDA="miboveda"

TYPES=($MIBOVEDA)
APP_MACOS_TYPE=$1

if [ -n "$1" ]; then
	APP_MACOS_TYPE=$1
fi

MIBOVEDA_NAME="Mi Bóveda"
MIBOVEDA_VERSION="1.0.0"
MIBOVEDA_BUILD_NUMBER=1
MIBOVEDA_BUNDLE_ID="com.miboveda.wallet"

if ! [[ " ${TYPES[*]} " =~ " ${APP_MACOS_TYPE} " ]]; then
    echo "Wrong app type."
    exit 1
fi

case $APP_MACOS_TYPE in
	$MIBOVEDA)
		APP_MACOS_NAME=$MIBOVEDA_NAME
		APP_MACOS_VERSION=$MIBOVEDA_VERSION
		APP_MACOS_BUILD_NUMBER=$MIBOVEDA_BUILD_NUMBER
		APP_MACOS_BUNDLE_ID=$MIBOVEDA_BUNDLE_ID;;
esac

export APP_MACOS_TYPE
export APP_MACOS_NAME
export APP_MACOS_VERSION
export APP_MACOS_BUILD_NUMBER
export APP_MACOS_BUNDLE_ID
